version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: easybank_postgres
    restart: always
    environment:
      POSTGRES_DB: Easy_bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: easybank_app
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: db-docker
    ports:
      - "8080:8080"

volumes:
  pg_data: